### ISSUE TITLE
Issues with the Typescript types of this package

### ISSUE THREAD

**Issue by Svish** [extractus/oembed-extractor#175]
The type returned by `extract` seems to be thought as a discriminated union, but the way it's written, it doesn't actually work as one.

This means it for example is not possible to access the `html` property of a response with `type: 'video'`, even after checking that the `type` is indeed `'video'`.
```ts
import { extract } from '@extractus/oembed-extractor'

const data = await extract('https://vimeo.com/6428069');

switch(data.type) {
    case 'video':
        console.log(data.html)
        break;
}
```
[Exampe on TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUwB4ygQwMbwL5wBmUEIcA5AAJoY4wCuAzgPQTIgBGyAJgLQ1Zc0cgFgAUOOwQAdo3jdMMTHAC8cTAHdMweALoAKcgAsYMMIwBczZgDdQyCADopIZgDYALACYAHAAY3AE5yAEoAbnFxRg0dbCN9BSVHGABPMGQQxHE4HLhsTEZkCjtuB3ILbNyqqVkIABtkRzqIAHMExUxHExA6kMqqnI4oZEwAawixPHEgA)

I also notice there's a lot of optional fields on all the types in this project. Would be good if they could be non-optional, so we don't have to constantly check whether something is there or not.

**Comment by ndaidong** [comment]
@Svish thank you for you notice, could you modify the type definitions and make a pr?

**Comment by chpio** [comment]
I'm still having the same problem, version 4.0.3.
